apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: docker-registry
  labels:
    k8s-app: registry-proxy
spec:
  template:
    metadata:
      labels:
        k8s-app: registry-proxy
    spec:
      containers:
        - image: docker.io/haproxy
          imagePullPolicy: Always
          name: registry-proxy
          ports:
            - containerPort: 5000
              hostPort: 5000
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
