apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonar
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar
          image: sonarqube:7.1
          volumeMounts:
          - mountPath: "/opt/sonar/data/"
            name: sonar-volume
          - mountPath: "/opt/sonar/extensions/"
            name: sonar-extensions
          env:
          - name: "SONARQUBE_JDBC_USERNAME"
            value: "sonar"
          - name: "SONARQUBE_JDBC_URL"
            value: "jdbc:postgresql://10.1.1.5:5435/sonar"
          - name: "SONARQUBE_JDBC_PASSWORD"
            value: "sonar"
          ports:
          - containerPort: 9000
            protocol: TCP
      volumes:
      - name: sonar-volume
        persistentVolumeClaim:
          claimName: sonar-volume
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  selector:
    app: sonar
  ports:
  - name: sonar-http
    port: 9000
    targetPort: 9000
    nodePort: 31121
  type: NodePort

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-pv-root
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sonar"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node3
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-pv-ext
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sonar-ext"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node3

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-volume
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-extensions
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
