apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  selector:
    app: sonar
  ports:
    - name: sonar-http
      port: 9000
      targetPort: 9000
      nodePort: 31121
  type: NodePort