kind: PersistentVolume
apiVersion: v1
metadata:
  name: bitbucket-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/bitbucket"
  nodeAffinity: #FIXME
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-node1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitbucket-volume
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

