apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-deployment
  labels:
    app: bitbucket
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
      - name: bitbucket
        image: atlassian/bitbucket-server
        ports:
        - containerPort: 7990
          name: bitbucket-http
        - containerPort: 22
          name: bitbucket-ssh
        volumeMounts:
        - mountPath: /var/atlassian/application-data/bitbucket
          name: bitbucket-data
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-volume
---
apiVersion: v1
kind: Service
metadata:
  name: bitbucket-service
spec:
  selector:
    app: bitbucket
  ports:
  - name: bitbucket-http
    port: 7990
    targetPort: bitbucket-http
    nodePort: 31119
  - name: bitbucket-ssh
    port: 2222
    targetPort: bitbucket-ssh
    nodePort: 31120
  type: NodePort

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: bitbucket-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/bitbucket"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node1

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitbucket-volume
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

