apiVersion: v1
kind: Service
metadata:
  name: hsr-service
  namespace: default
  labels:
    app: hsr
spec:
  type: NodePort
  selector:
    app: hsr
  ports:
    - name: hsr-tcp
      nodePort: 31120
      port: 9090
      targetPort: 9090
      protocol: TCP
