apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-hcr
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-hcr
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        app: mysql-hcr
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-hcr
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: hcr-secret
                  key: mysql-root
            - name: "MYSQL_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: hcr-secret
                  key: hcr-database
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: hcr-secret
                  key: hcr-username
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: hcr-secret
                  key: hcr-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysqld-conf
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-hcr-claim
        - name: mysqld-conf
          configMap:
            name: mysql
            items:
              - key: mysqld.cnf
                path: mysqld.cnf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: default
data:
  mysqld.cnf: |-
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    log-error      = /var/log/mysql/error.log
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    bind-address = 0.0.0.0