apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-hcr-claim
  namespace: default
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi