apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: hsm-nexus
  name: hsm-nexus
  namespace: hsm-ui
spec:
  replicas: 1
  selector:
    app: hsm-nexus
    deploymentconfig: hsm-nexus
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 300
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: hsm-nexus
        deploymentconfig: hsm-nexus
    spec:
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-master-data
      containers:
      - image: sonatype/nexus3:3.16.1
        imagePullPolicy: IfNotPresent
        name: hsm-nexus
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange