apiVersion: v1
kind: Service
metadata:
  name: nexus-ui
spec:
  selector:
    app: hsm-nexus
  ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081

---
apiVersion: v1
kind: Route
metadata:
  annotations:
  name: nexus
  namespace: hsm-ui
spec:
  port:
    targetPort: 8081-tcp
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: nexus-ui
    weight: 100
  wildcardPolicy: None
